/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei/useGLTF'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/glasstest.gltf')
  return (
    <group ref={group} {...props} dispose={null}>
      <group position={[-0.06, -0.07, -0.04]} scale={[0.25, 0.25, 0.25]}>
        <primitive object={nodes.spine} />
        <skinnedMesh
          material={materials['Material.003']}
          geometry={nodes.STIKLAS_1.geometry}
          skeleton={nodes.STIKLAS_1.skeleton}
        />
        <skinnedMesh
          material={materials['Material.004']}
          geometry={nodes.STIKLAS_2.geometry}
          skeleton={nodes.STIKLAS_2.skeleton}
        />
        <skinnedMesh
          material={materials['Material.001']}
          geometry={nodes.STIKLAS_3.geometry}
          skeleton={nodes.STIKLAS_3.skeleton}
        />
        <skinnedMesh
          material={materials['Material.009']}
          geometry={nodes.STIKLAS_4.geometry}
          skeleton={nodes.STIKLAS_4.skeleton}
        />
        <skinnedMesh
          material={materials['Material.008']}
          geometry={nodes.STIKLAS_5.geometry}
          skeleton={nodes.STIKLAS_5.skeleton}
        />
        <skinnedMesh
          material={materials['Material.002']}
          geometry={nodes.STIKLAS_6.geometry}
          skeleton={nodes.STIKLAS_6.skeleton}
        />
        <skinnedMesh
          material={materials['Material.006']}
          geometry={nodes.STIKLAS_7.geometry}
          skeleton={nodes.STIKLAS_7.skeleton}
        />
      </group>
    </group>
  )
}

useGLTF.preload('/glasstest.gltf')
