/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from "three";
import React, { useRef, useState, useEffect } from "react";
import { useFrame } from "react-three-fiber";
import { useGLTF } from "@react-three/drei/useGLTF";

import { useAnimations } from "@react-three/drei/useAnimations";

export default function Model(props) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF("/keturilapai.gltf");
  const { actions } = useAnimations(animations, group);
  useEffect(() => {
    console.log(actions);
    actions["Armature.001Action"].play();
    actions["Armature.002Action"].play();
    actions["Armature.003Action"].play();
    actions["ArmatureAction"].play();
  });
  return (
    <group ref={group} {...props} dispose={null}>
      <group position={[0, -1.86, -0.54]}>
        <primitive object={nodes.Bone} />
        <skinnedMesh
          material={materials["Material.003"]}
          geometry={nodes.Plane_1.geometry}
          skeleton={nodes.Plane_1.skeleton}
        />
        <skinnedMesh
          material={materials.Material}
          geometry={nodes.Plane_2.geometry}
          skeleton={nodes.Plane_2.skeleton}
        />
        <skinnedMesh
          material={materials["Material.003"]}
          geometry={nodes.Text.geometry}
          skeleton={nodes.Text.skeleton}
        />
      </group>
      <group position={[0, -1.89, -0.54]} rotation={[-Math.PI, 0, 0]}>
        <primitive object={nodes.Bone_1} />
        <skinnedMesh
          material={materials["Material.003"]}
          geometry={nodes.Plane002_1.geometry}
          skeleton={nodes.Plane002_1.skeleton}
        />
        <skinnedMesh
          material={materials.Material}
          geometry={nodes.Plane002_2.geometry}
          skeleton={nodes.Plane002_2.skeleton}
        />
      </group>
      <group position={[0, -1.86, 0.55]}>
        <primitive object={nodes.Bone_2} />
        <skinnedMesh
          material={materials["Material.003"]}
          geometry={nodes.Plane004.geometry}
          skeleton={nodes.Plane004.skeleton}
        />
        <skinnedMesh
          material={materials.Material}
          geometry={nodes.Plane004_1.geometry}
          skeleton={nodes.Plane004_1.skeleton}
        />
      </group>
      <group position={[0, -1.89, 0.55]} rotation={[-Math.PI, 0, 0]}>
        <primitive object={nodes.Bone_3} />
        <skinnedMesh
          material={materials["Material.003"]}
          geometry={nodes.Plane003_1.geometry}
          skeleton={nodes.Plane003_1.skeleton}
        />
        <skinnedMesh
          material={materials.Material}
          geometry={nodes.Plane003_2.geometry}
          skeleton={nodes.Plane003_2.skeleton}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/keturilapai.gltf");
