/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei/useGLTF";
import { useFrame } from "react-three-fiber";

export default function Model(props) {
  const group = useRef();
  console.log(group);
  // useFrame(() => {
  //   group.current.position.x = group.current.position.x + 0.03;
  //   group.current.rotation.x = group.current.rotation.x + 0.02;
  // });
  const { nodes, materials } = useGLTF("/kosmonautas.gltf");
  return (
    <group ref={group} {...props} dispose={null}>
      <group position={[-0.06, -0.07, -0.04]} scale={[0.25, 0.25, 0.25]}>
        <primitive object={nodes.spine} />
        <skinnedMesh
          material={materials["Material.003"]}
          geometry={nodes.kosmonautasvienas_1.geometry}
          skeleton={nodes.kosmonautasvienas_1.skeleton}
        />
        <skinnedMesh
          material={materials["Material.004"]}
          geometry={nodes.kosmonautasvienas_2.geometry}
          skeleton={nodes.kosmonautasvienas_2.skeleton}
        />
        <skinnedMesh
          material={materials["Material.001"]}
          geometry={nodes.kosmonautasvienas_3.geometry}
          skeleton={nodes.kosmonautasvienas_3.skeleton}
        />
        <skinnedMesh
          material={materials["Material.009"]}
          geometry={nodes.kosmonautasvienas_4.geometry}
          skeleton={nodes.kosmonautasvienas_4.skeleton}
        />
        <skinnedMesh
          material={materials["Material.008"]}
          geometry={nodes.kosmonautasvienas_5.geometry}
          skeleton={nodes.kosmonautasvienas_5.skeleton}
        />

        <skinnedMesh
          material={materials["Material.002"]}
          geometry={nodes.kosmonautasvienas_6.geometry}
          skeleton={nodes.kosmonautasvienas_6.skeleton}
        />

        <skinnedMesh
          material={materials["Material.006"]}
          geometry={nodes.kosmonautasvienas_7.geometry}
          skeleton={nodes.kosmonautasvienas_7.skeleton}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/kosmonautas.gltf");
