/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei/useGLTF'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/remas.gltf')
  return (
    <group ref={group} {...props} dispose={null}>
      <group position={[0, -1.09, 0]} scale={[0.12, 0.12, 0.12]}>
        <mesh material={materials['Material.004']} geometry={nodes.Cylinder003.geometry} />
        <mesh material={materials['Material.003']} geometry={nodes.Cylinder003_1.geometry} />
        <mesh material={materials['Material.001']} geometry={nodes.Cylinder003_2.geometry} />
        <mesh material={materials['Material.005']} geometry={nodes.Cylinder003_3.geometry} />
        <mesh material={materials.Material} geometry={nodes.Cylinder003_4.geometry} />
        <mesh material={materials['Material.002']} geometry={nodes.Cylinder003_5.geometry} />
      </group>
    </group>
  )
}

useGLTF.preload('/remas.gltf')
