/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei/useGLTF'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/SATALITAS.gltf')
  return (
    <group ref={group} {...props} dispose={null}>
      <group position={[0, -1.88, 0.7]} rotation={[-Math.PI / 2, 0, 0]} scale={[0.02, 0.02, 0.02]}>
        <mesh material={materials['Material.001']} geometry={nodes.SATALITE_1.geometry} />
        <mesh material={materials['Material.005']} geometry={nodes.SATALITE_2.geometry} />
        <mesh material={materials['Material.003']} geometry={nodes.SATALITE_3.geometry} />
        <mesh material={materials['Material.002']} geometry={nodes.SATALITE_4.geometry} />
        <mesh material={materials['Material.004']} geometry={nodes.SATALITE_5.geometry} />
        <mesh material={materials.Material} geometry={nodes.SATALITE_6.geometry} />
      </group>
    </group>
  )
}

useGLTF.preload('/SATALITAS.gltf')
