/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei/useGLTF'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/veidrodis.gltf')
  return (
    <group ref={group} {...props} dispose={null}>
      <group position={[0.35, -0.05, 1.47]} scale={[4.11, 4.11, 4.11]}>
        <mesh material={materials['Material.003']} geometry={nodes.veidrodis_1.geometry} />
        <mesh material={materials['Material.004']} geometry={nodes.veidrodis_2.geometry} />
        <mesh material={materials['Material.001']} geometry={nodes.veidrodis_3.geometry} />
        <mesh material={materials['Material.009']} geometry={nodes.veidrodis_4.geometry} />
        <mesh material={materials['Material.008']} geometry={nodes.veidrodis_5.geometry} />
        <mesh material={materials.Blue} geometry={nodes.veidrodis_6.geometry} />
        <mesh material={materials['Material.006']} geometry={nodes.veidrodis_7.geometry} />
      </group>
    </group>
  )
}

useGLTF.preload('/veidrodis.gltf')
