/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei/useGLTF";
import { useFrame } from "react-three-fiber";

export default function Model(props) {
  const group = useRef();
  const { nodes, materials } = useGLTF("/ZEME.gltf");

  useFrame(() => {
    group.current.rotation.x = group.current.rotation.x + 0.02;
  });
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[1.18, 0, 0]}>
        <mesh material={materials.Green} geometry={nodes.ZEME_1.geometry} />
        <mesh material={materials.Blue} geometry={nodes.ZEME_2.geometry} />
        <mesh material={materials.Snow} geometry={nodes.ZEME_3.geometry} />
        <mesh material={materials.Brown} geometry={nodes.ZEME_4.geometry} />
        <mesh material={materials.DarkGreen} geometry={nodes.ZEME_5.geometry} />
      </group>
    </group>
  );
}

useGLTF.preload("/ZEME.gltf");
